services:
  redisai:
    container_name: redisai
    image: redislabs/redisai:edge-gpu-bionic
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    ports:
      - 6379:6379
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]

  fastapi:
    container_name: fastapi
    build: .
    command: gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --access-logfile - --log-level info --bind 0.0.0.0:80
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      # - .:/home/code
      - ./src:/home/code/src
      - ./models:/home/code/models
      - ./scripts:/home/code/scripts
      - ./served-models:/home/code/served-models
    entrypoint:
      - sh
      - scripts/docker_entrypoint.sh

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    env_file:
      - .env
    network_mode: host
    command: ["http", "80"]